openapi: 3.0.3
x-envelope: jsonrpc-2.0
info:
  title: 'Прокси сервис для внешних интеграций'
  description: |
    Используется протокол JSON-RPC 2.0

    [Ссылка на общий контракт](https://github.com/vea-company/vea-company.github.io/blob/main/json-rpc-contract/README.md)
  version: 1.0.0
tags:
  -
    name: pay-out-transactions
    description: 'Транзакции на вывод'
  -
    name: pay-in-transactions
    description: 'Заказы на пополнение'
servers:
  -
    url: 'http://v81.server.soc/json-rpc'
    description: 'Develop server'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
paths:
  '/pay-in-transactions.create#1f86a79f':
    $ref: './pay-in-transactions/create-1f86a79f.yaml#/paths/create'
  '/pay-in-transactions.create#3aea838f':
    $ref: './pay-in-transactions/create-3aea838f.yaml#/paths/create'
  '/pay-in-transactions.create#3e6c06de':
    $ref: './pay-in-transactions/create-3e6c06de.yaml#/paths/create'
  '/pay-in-transactions.create#cfea1576':
    $ref: './pay-in-transactions/create-cfea1576.yaml#/paths/create'
  '/pay-in-transactions.create#d2821d0d':
    $ref: './pay-in-transactions/create-d2821d0d.yaml#/paths/create'
  '/pay-in-transactions.create#da450505':
    $ref: './pay-in-transactions/create-da450505.yaml#/paths/create'
  '/pay-in-transactions.create#df6c0ff6':
    $ref: './pay-in-transactions/create-df6c0ff6.yaml#/paths/create'
  '/pay-in-transactions.one-by-id#2a1a2066':
    $ref: './pay-in-transactions/one-by-id-2a1a2066.yaml#/paths/one-by-id'
  '/pay-in-transactions.one-by-id#fae18ad8':
    $ref: './pay-in-transactions/one-by-id-fae18ad8.yaml#/paths/one-by-id'
  '/pay-out-transactions.create#1ca8c0d7':
    $ref: './pay-out-transactions/create-1ca8c0d7.yaml#/paths/create'
  '/pay-out-transactions.create#5a798908':
    $ref: './pay-out-transactions/create-5a798908.yaml#/paths/create'
  '/pay-out-transactions.create#68670641':
    $ref: './pay-out-transactions/create-68670641.yaml#/paths/create'
  '/pay-out-transactions.create#b38c7ee6':
    $ref: './pay-out-transactions/create-b38c7ee6.yaml#/paths/create'
  '/pay-out-transactions.one-by-id#db39c1e3':
    $ref: './pay-out-transactions/one-by-id-db39c1e3.yaml#/paths/one-by-id'
